import datetime
from copy import deepcopy
import pprint
import datetime
EmpSummary = {'name': 'nandan', 'totalMonthlySalary': 40000.0, 'dailySalary': 1333.33, 'CalculatedSalary': 42266.7,
              'totalSundaysAbsent': 0, 'totalHolidaytaken': 1, 'totalHolidaysAllowed': 4, 'totalHolidaysWorked': 0,
              'totalWorkdays': 30, 'totalTimesLate': 13, 'totalAdditions': 3999.99, 'totaldeductions': 1733.29}

SummaryHeader = ['name', 'totalMonthlySalary', 'dailySalary', 'totalHolidaysAllowed', 'totalHolidaytaken',
                 'totalHolidaysWorked', 'totalSundaysAbsent',
                 'totalTimesLate', 'totaldeductions', 'totalAdditions', 'CalculatedSalary'
                 ]

TimeHeader = ['day', 'dayOfWeek', 'shiftStart', 'shiftEnd', 'shiftWorkHours', 'shiftType', 'shiftComment',
              'EmpTimeIn', 'EmpTimeOut', 'EnforcedEmpTimeIn', 'EnforcedEmpTimeOut',
              'totalHoursLate', 'totalHoursLate', 'Absent', 'halfDay', 'HolidayCredit', 'PercentSalaryAdditions',
              'PercentDeductions', 'DailyAdditions', 'DailyDeductions'
              ]

temp=[]
for key in SummaryHeader:
    temp.append(EmpSummary[key])

del temp[:]
Details= [{'day': datetime.datetime(2018, 1, 3, 0, 0), 'dayOfWeek': 'Thu',
             'shiftStart': datetime.datetime(2018, 1, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 1, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 1, 3, 10, 21, 59),
             'EmpTimeOut': datetime.datetime(2018, 1, 3, 19, 0, 59),
             'EnforcedEmpTimeIn': datetime.datetime(2018, 1, 3, 10, 30), 'totalHoursLate': 0, 'PercentDeductions': 0,
             'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
             'HolidayCredit': 0, 'DailyDeductions': 0, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 2, 3, 0, 0), 'dayOfWeek': 'Fri',
             'shiftStart': datetime.datetime(2018, 2, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 2, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 2, 3, 0, 0),
             'EmpTimeOut': datetime.datetime(2018, 2, 3, 0, 0), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 0,
             'PercentDeductions': 0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 1,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 0, 'DailyAdditions': 0,
             'shiftWorkHours': 10}, {'day': datetime.datetime(2018, 3, 3, 0, 0), 'dayOfWeek': 'Sat',
                                     'shiftStart': datetime.datetime(2018, 3, 3, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 3, 3, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 3, 10, 37, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 3, 3, 20, 0, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 1.0, 'PercentDeductions': 10.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 4, 3, 0, 0), 'dayOfWeek': 'Sun',
             'shiftStart': datetime.datetime(2018, 4, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 4, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 4, 3, 10, 30, 59),
             'EmpTimeOut': datetime.datetime(2018, 4, 3, 0, 0), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 0.0,
             'PercentDeductions': 0.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 1, 'Absent': 0,
             'EnforcedEmpTimeOut': datetime.datetime(2018, 4, 3, 15, 30), 'HolidayCredit': 0, 'DailyDeductions': 0.0,
             'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 5, 3, 0, 0), 'dayOfWeek': 'Mon',
             'shiftStart': datetime.datetime(2018, 5, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 5, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 5, 3, 10, 36, 59),
             'EmpTimeOut': datetime.datetime(2018, 5, 3, 20, 1, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
          {'day': datetime.datetime(2018, 6, 3, 0, 0), 'dayOfWeek': 'Tue',
                                     'shiftStart': datetime.datetime(2018, 6, 3, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 6, 3, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 6, 3, 11, 5, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 6, 3, 20, 1, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 1.0, 'PercentDeductions': 10.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 7, 3, 0, 0), 'dayOfWeek': 'Wed',
             'shiftStart': datetime.datetime(2018, 7, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 7, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 7, 3, 10, 38, 59),
             'EmpTimeOut': datetime.datetime(2018, 7, 3, 20, 0, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 8, 3, 0, 0), 'dayOfWeek': 'Thu',
                                     'shiftStart': datetime.datetime(2018, 8, 3, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 8, 3, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 8, 3, 10, 45, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 8, 3, 18, 11, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 1.0, 'PercentDeductions': 10.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 9, 3, 0, 0), 'dayOfWeek': 'Fri',
             'shiftStart': datetime.datetime(2018, 9, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 9, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 9, 3, 10, 37, 59),
             'EmpTimeOut': datetime.datetime(2018, 9, 3, 20, 2, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
          {'day': datetime.datetime(2018, 10, 3, 0, 0), 'dayOfWeek': 'Sat',
                                     'shiftStart': datetime.datetime(2018, 10, 3, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 10, 3, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 10, 3, 10, 37, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 10, 3, 20, 1, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 1.0, 'PercentDeductions': 10.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 11, 3, 0, 0), 'dayOfWeek': 'Sun',
             'shiftStart': datetime.datetime(2018, 11, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 11, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 11, 3, 10, 37, 59),
             'EmpTimeOut': datetime.datetime(2018, 11, 3, 0, 0), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 1, 'Absent': 0,
             'EnforcedEmpTimeOut': datetime.datetime(2018, 11, 3, 15, 30), 'HolidayCredit': 0,
             'DailyDeductions': 133.33, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 12, 3, 0, 0), 'dayOfWeek': 'Mon',
             'shiftStart': datetime.datetime(2018, 12, 3, 10, 30), 'shiftEnd': datetime.datetime(2018, 12, 3, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 12, 3, 10, 37, 59),
             'EmpTimeOut': datetime.datetime(2018, 12, 3, 20, 5, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 13, 0, 0), 'dayOfWeek': 'Tue',
                                     'shiftStart': datetime.datetime(2018, 3, 13, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 3, 13, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 13, 10, 33, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 3, 13, 20, 1, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 0.0, 'PercentDeductions': 0.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 0.0, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 14, 0, 0), 'dayOfWeek': 'Wed',
             'shiftStart': datetime.datetime(2018, 3, 14, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 14, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 14, 10, 23, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 14, 0, 0),
             'EnforcedEmpTimeIn': datetime.datetime(2018, 3, 14, 10, 30), 'totalHoursLate': 0, 'PercentDeductions': 0,
             'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
             'HolidayCredit': 0, 'DailyDeductions': 0, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 15, 0, 0), 'dayOfWeek': 'Thu',
             'shiftStart': datetime.datetime(2018, 3, 15, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 15, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 15, 10, 27, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 15, 20, 0, 59),
             'EnforcedEmpTimeIn': datetime.datetime(2018, 3, 15, 10, 30), 'totalHoursLate': 0, 'PercentDeductions': 0,
             'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
             'HolidayCredit': 0, 'DailyDeductions': 0, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 16, 0, 0), 'dayOfWeek': 'Fri',
             'shiftStart': datetime.datetime(2018, 3, 16, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 16, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 16, 10, 43, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 16, 0, 0), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 1, 'Absent': 0,
             'EnforcedEmpTimeOut': datetime.datetime(2018, 3, 16, 15, 30), 'HolidayCredit': 0,
             'DailyDeductions': 133.33, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 17, 0, 0), 'dayOfWeek': 'Sat',
             'shiftStart': datetime.datetime(2018, 3, 17, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 17, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 17, 10, 33, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 17, 20, 2, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 0.0,
             'PercentDeductions': 0.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 0.0, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 18, 0, 0), 'dayOfWeek': 'Sun',
                                     'shiftStart': datetime.datetime(2018, 3, 18, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 3, 18, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 18, 10, 18, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 3, 18, 18, 30, 59),
                                     'EnforcedEmpTimeIn': datetime.datetime(2018, 3, 18, 10, 30), 'totalHoursLate': 0,
                                     'PercentDeductions': 0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0,
                                     'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '', 'HolidayCredit': 0,
                                     'DailyDeductions': 0, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 19, 0, 0), 'dayOfWeek': 'Mon',
             'shiftStart': datetime.datetime(2018, 3, 19, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 19, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 19, 10, 31, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 19, 20, 0, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 0.0,
             'PercentDeductions': 0.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 0.0, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
          {'day': datetime.datetime(2018, 3, 20, 0, 0), 'dayOfWeek': 'Tue',
                                     'shiftStart': datetime.datetime(2018, 3, 20, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 3, 20, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 20, 10, 31, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 3, 20, 20, 0, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 0.0, 'PercentDeductions': 0.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 0.0, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 21, 0, 0), 'dayOfWeek': 'Wed',
             'shiftStart': datetime.datetime(2018, 3, 21, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 21, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 21, 10, 35, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 21, 20, 0, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
          {'day': datetime.datetime(2018, 3, 22, 0, 0), 'dayOfWeek': 'Thu',
                                     'shiftStart': datetime.datetime(2018, 3, 22, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 3, 22, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 22, 10, 16, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 3, 22, 20, 1, 59),
                                     'EnforcedEmpTimeIn': datetime.datetime(2018, 3, 22, 10, 30), 'totalHoursLate': 0,
                                     'PercentDeductions': 0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0,
                                     'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '', 'HolidayCredit': 0,
                                     'DailyDeductions': 0, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 23, 0, 0), 'dayOfWeek': 'Fri',
             'shiftStart': datetime.datetime(2018, 3, 23, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 23, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 23, 10, 30),
             'EmpTimeOut': datetime.datetime(2018, 3, 23, 20, 0, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 0.0,
             'PercentDeductions': 0.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 0.0, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
          {'day': datetime.datetime(2018, 3, 24, 0, 0), 'dayOfWeek': 'Sat',
                                     'shiftStart': datetime.datetime(2018, 3, 24, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 3, 24, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 24, 10, 51, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 3, 24, 19, 0, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 1.0, 'PercentDeductions': 10.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 25, 0, 0), 'dayOfWeek': 'Sun',
             'shiftStart': datetime.datetime(2018, 3, 25, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 25, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 25, 10, 26, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 25, 19, 7, 59),
             'EnforcedEmpTimeIn': datetime.datetime(2018, 3, 25, 10, 30), 'totalHoursLate': 0, 'PercentDeductions': 0,
             'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
             'HolidayCredit': 0, 'DailyDeductions': 0, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 26, 0, 0), 'dayOfWeek': 'Mon',
             'shiftStart': datetime.datetime(2018, 3, 26, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 26, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 26, 10, 34, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 26, 19, 0, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 0.0,
             'PercentDeductions': 0.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 0.0, 'DailyAdditions': 0,
             'shiftWorkHours': 10},
          {'day': datetime.datetime(2018, 3, 27, 0, 0), 'dayOfWeek': 'Tue',
                                     'shiftStart': datetime.datetime(2018, 3, 27, 10, 30),
                                     'shiftEnd': datetime.datetime(2018, 3, 27, 20, 30), 'shiftType': 'shift1',
                                     'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 27, 10, 32, 59),
                                     'EmpTimeOut': datetime.datetime(2018, 3, 27, 19, 6, 59), 'EnforcedEmpTimeIn': '',
                                     'totalHoursLate': 0.0, 'PercentDeductions': 0.0, 'overTimeHours': 0,
                                     'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
                                     'HolidayCredit': 0, 'DailyDeductions': 0.0, 'DailyAdditions': 0,
                                     'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 28, 0, 0), 'dayOfWeek': 'Wed',
             'shiftStart': datetime.datetime(2018, 3, 28, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 28, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 28, 10, 23, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 28, 0, 0),
             'EnforcedEmpTimeIn': datetime.datetime(2018, 3, 28, 10, 30), 'totalHoursLate': 0, 'PercentDeductions': 0,
             'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0, 'EnforcedEmpTimeOut': '',
             'HolidayCredit': 0, 'DailyDeductions': 0, 'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': datetime.datetime(2018, 3, 29, 0, 0), 'dayOfWeek': 'Thu',
             'shiftStart': datetime.datetime(2018, 3, 29, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 29, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 29, 10, 34, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 29, 0, 0), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 0.0,
             'PercentDeductions': 0.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 1, 'Absent': 0,
             'EnforcedEmpTimeOut': datetime.datetime(2018, 3, 29, 15, 30), 'HolidayCredit': 0, 'DailyDeductions': 0.0,
             'DailyAdditions': 0, 'shiftWorkHours': 10},
            {'day': "", 'dayOfWeek': 'Fri',
             'shiftStart': datetime.datetime(2018, 3, 30, 10, 30), 'shiftEnd': datetime.datetime(2018, 3, 30, 20, 30),
             'shiftType': 'shift1', 'shiftComment': '', 'EmpTimeIn': datetime.datetime(2018, 3, 30, 10, 39, 59),
             'EmpTimeOut': datetime.datetime(2018, 3, 30, 20, 1, 59), 'EnforcedEmpTimeIn': '', 'totalHoursLate': 1.0,
             'PercentDeductions': 10.0, 'overTimeHours': 0, 'PercentSalaryAdditions': 0, 'halfDay': 0, 'Absent': 0,
             'EnforcedEmpTimeOut': '', 'HolidayCredit': 0, 'DailyDeductions': 133.33, 'DailyAdditions': 0,
             'shiftWorkHours': 10}
            ]

monthlyArr=[]
for dayObj in Details:
    for key in TimeHeader:
        if key == 'day':
            ftstr=""
            if isinstance(dayObj[key],datetime.date) and dayObj[key] is not None or dayObj[key] != '':
                ftstr=dayObj[key].strftime('%x')
            else:
                ftstr = "NA"
        if key in ['shiftStart', 'shiftEnd', 'EmpTimeIn', 'EmpTimeOut', 'EnforcedEmpTimeIn', 'EnforcedEmpTimeOut', ]:
            ftstr = ""
            if isinstance(dayObj[key], datetime.date) and dayObj[key] is not None or dayObj[key] != '':
                ftstr = dayObj[key].strftime('%X')
            else:
                ftstr = "NA"
        temp.append(ftstr)
    monthlyArr.append(deepcopy(temp))
    del temp[:]

pp = pprint.PrettyPrinter(indent=4)
print(len(monthlyArr))

pp.pprint(monthlyArr)

